name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 4'

jobs:
  get-releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.generate-matrix.outputs.releases }}
    steps:
      - name: generate matrix
        id: generate-matrix
        run: |
          function join_by { local d=$1; shift; local f=$1; shift; printf %s "$f" "${@/#/$d}"; }
          RELEASE_JSON="[$(join_by , $(curl -sL https://releases.openstack.org/ | sed -En 's|.*<a class="reference internal" href="[a-z]+/index\.html"><span class="doc">([a-zA-Z]+)</span></a>.*|"\1"|p' | tail -n +3))]"
          echo "${RELEASE_JSON,,}"
          echo "::set-output name=releases::${RELEASE_JSON,,}"
  docker:
    needs: get-releases
    strategy:
      matrix:
        release: ${{ fromJson(needs.get-releases.outputs.releases) }}
        include:
          - release: ussuri
            centos_release: 8
          - release: victoria
            centos_release: 8
        exclude:
          # exclude all the ones not in the centos vault
          - release: austin
          - release: bexar
          - release: cactus
          - release: diablo
          - release: essex
          - release: folsom
          - release: grizzly
          - release: havana
          - release: icehouse
          - release: juno
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            squarebracket/openstack-client
          tag-custom: ${{ matrix.release }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set centos version
        id: set-centos-version
        env:
          CENTOS_VERSION: ${{ matrix.centos_release }}
        run: |
          echo "::set-output name=centos_version::${CENTOS_VERSION:-7}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            centos_version=${{ steps.set-centos-version.outputs.centos_version }}
            openstack_release=${{ matrix.release }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
